### ISSUE TITLE
Total Price is not resetting

### ISSUE THREAD

**Issue by SireenAtGitHub** [SireenAtGithub/custom-invoice#11]
When a user has filled all the data and successfully generated the PDF. all the fields are getting reset on the page but not the Total Price field. It stays the same as calculated in the recently generated invoice. **The issue happens when there is only one item in the invoice.**

![image](https://user-images.githubusercontent.com/78824038/167287474-2f81b470-2034-4d70-bfd8-5fafe56843ac.png)

![image](https://user-images.githubusercontent.com/78824038/167287497-57d3ff4f-c08f-4626-972b-e5515fd81485.png)

![image](https://user-images.githubusercontent.com/78824038/167287509-91175eaf-e111-4a07-8f66-9d02dc489cd1.png)

In the last image as you can see the field stayed the same. 

- [x] Resolve the above issue
- [x] Change the price text to amount  (Total Price -> Total Amount), ( Enter Price -> Enter Amount) . Just to make it relevant to the site.

**Comment by kiteretsu-daihyakka** [comment]
Yes, this bug I am able to reproduce. I am checking on it. Creating a new branch for the same.

**Comment by SireenAtGitHub** [comment]
PRs are Merged. branches can be deleted.
