### ISSUE TITLE
Invoice is not getting generated when DEBUG = False.

### ISSUE THREAD

**Issue by SireenAtGitHub** [SireenAtGithub/custom-invoice#16]
The issue is deep and would need a strong solution. When we set DEBUG value as false it returns 500 server error and below logs. The issue needs discussion. I was able to get the logs of the errors.

One drive link of the logs: https://1drv.ms/u/s!AuUPtl7cMxEvhQmIORC4OiZ_FO1B?e=gCR3Rz

Look into it and let me know your availability. @kiteretsu-daihyakka

**Comment by kiteretsu-daihyakka** [comment]
Sure, Let us get into an offline call to analysis the issue.

**Comment by SireenAtGitHub** [comment]
Closing the issue as it is resolved now. 

[Commit](https://github.com/SireenAtGithub/custom-invoice/commit/adf508fcebc433a2679cddc4b1a6690bd44bd4c8)
