### ISSUE TITLE
TECH SPIKE - Insert bootstrap validations instead of alert boxes.

### ISSUE THREAD

**Issue by SireenAtGitHub** [SireenAtGithub/custom-invoice#24]
There are several places where we are sending out messages in alert box validations. the alert box validations can be converted into the following type of validations.

![image](https://user-images.githubusercontent.com/78824038/169680186-158e5263-9c43-4b1a-9710-e290d4b27530.png)

https://getbootstrap.com/docs/5.0/forms/validation/

@kiteretsu-daihyakka  - Let's see how we can update the validation messages.

**Comment by kiteretsu-daihyakka** [comment]
Sure, We'll connect for the same!

**Comment by SireenAtGitHub** [comment]
@kiteretsu-daihyakka  - Starting to work on it with one field. let's see how it goes
