### ISSUE TITLE
page reloads after generating pdf

### ISSUE THREAD

**Issue by kiteretsu-daihyakka** [SireenAtGithub/custom-invoice#5]

**Comment by SireenAtGitHub** [comment]
Attach the pull request with the solution

**Comment by SireenAtGitHub** [comment]
FYI - I have modified the code to review the PDF before downloading the file. we have to download it with the download option in the PDF reviewer.

**Comment by kiteretsu-daihyakka** [comment]
Okay, thanks, I'll pull the latest code from master.
